// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvlogqjrchzjfvwtbqjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2bG9ncWpyY2h6amZ2d3RicWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTU3NTksImV4cCI6MjA2NDE3MTc1OX0.qS1OZuI-N_9Vo03K9mURPWhvCG_KXkKbxOw-U9gqMzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  }
);